frr version 8.4
hostname netflix
service integrated-vtysh-config

route-map ROUTE_MAP_IN permit 10
exit

ip prefix-list R6.1       permit 52.94.76.1/32
ip prefix-list R6.2       permit 52.94.76.2/32
ip prefix-list R6.3       permit 52.94.76.3/32

route-map ROUTE_MAP_OUT_R6_1 permit 10
 match ip address prefix-list R6.2
 set as-path prepend 2906
exit
route-map ROUTE_MAP_OUT_R6_1 permit 20
 match ip address prefix-list R6.3
 set as-path prepend 2906
exit
route-map ROUTE_MAP_OUT_R6_1 permit 30
exit


route-map ROUTE_MAP_OUT_R6_2 permit 10
 match ip address prefix-list R6.1
 set as-path prepend 2906
exit
route-map ROUTE_MAP_OUT_R6_2 permit 20
 match ip address prefix-list R6.3
 set as-path prepend 2906
exit
route-map ROUTE_MAP_OUT_R6_2 permit 30
exit


route-map ROUTE_MAP_OUT_R6_3 permit 10
 match ip address prefix-list R6.1
 set as-path prepend 2906
exit
route-map ROUTE_MAP_OUT_R6_3 permit 20
 match ip address prefix-list R6.2
 set as-path prepend 2906
exit
route-map ROUTE_MAP_OUT_R6_3 permit 30
exit


router bgp 2906
 bgp router-id 5.5.5.5
 bgp fast-external-failover
 no bgp ebgp-requires-policy
 
 neighbor 10.0.5.1 remote-as 205718
 neighbor 10.0.5.1 description R6.1
 neighbor 10.0.5.1 bfd

 neighbor 10.1.5.1 remote-as 205718
 neighbor 10.1.5.1 description R6.2
 neighbor 10.1.5.1 bfd

 neighbor 10.2.5.1 remote-as 205718
 neighbor 10.2.5.1 description R6.3
 neighbor 10.2.5.1 bfd

 address-family ipv4 unicast
  network 52.94.76.1/32
  network 52.94.76.2/32
  network 52.94.76.3/32
  
  neighbor 10.0.5.1 activate
  neighbor 10.0.5.1 soft-reconfiguration inbound
  neighbor 10.0.5.1 route-map ROUTE_MAP_IN in
  neighbor 10.0.5.1 route-map ROUTE_MAP_OUT_R6_1 out
  
  neighbor 10.1.5.1 activate
  neighbor 10.1.5.1 soft-reconfiguration inbound
  neighbor 10.1.5.1 route-map ROUTE_MAP_IN in
  neighbor 10.1.5.1 route-map ROUTE_MAP_OUT_R6_2 out
  
  neighbor 10.2.5.1 activate
  neighbor 10.2.5.1 soft-reconfiguration inbound
  neighbor 10.2.5.1 route-map ROUTE_MAP_IN in
  neighbor 10.2.5.1 route-map ROUTE_MAP_OUT_R6_3 out
  
  bgp bestpath as-path multipath-relax
  maximum-paths 8
exit
