frr version 8.4
hostname espanix
service integrated-vtysh-config

route-map ROUTE_MAP_IN permit 10
exit

ip prefix-list Google        permit 8.8.8.8/32
ip prefix-list Google        permit 8.8.4.4/32
ip prefix-list Netflix       permit 52.94.76.1/32
ip prefix-list Netflix       permit 52.94.76.2/32
ip prefix-list Netflix       permit 52.94.76.3/32
ip prefix-list Meta          permit 157.240.1.35/32
ip prefix-list Meta          permit 157.240.1.36/32
ip prefix-list Meta          permit 157.240.1.37/32

route-map ROUTE_MAP_OUT permit 10
 match ip address prefix-list Google
 set as-path prepend 65010 65010
exit
route-map ROUTE_MAP_OUT permit 20
 match ip address prefix-list Netflix
 set as-path prepend 65010 65010
exit
route-map ROUTE_MAP_OUT permit 30
 match ip address prefix-list Meta
 set as-path prepend 65010 65010
exit
route-map ROUTE_MAP_OUT permit 40
exit


router bgp 65010
 bgp router-id 3.3.3.3
 bgp fast-external-failover
 no bgp ebgp-requires-policy
 
 neighbor 10.0.3.1 remote-as 205718
 neighbor 10.0.3.1 description R6
 neighbor 10.0.3.1 bfd

 address-family ipv4 unicast
  network 195.69.144.1/32
  network 8.8.8.8/32
  network 8.8.4.4/32
  network 52.94.76.1/32
  network 52.94.76.2/32
  network 52.94.76.3/32
  network 157.240.1.35/32
  network 157.240.1.36/32
  network 157.240.1.37/32
  
  neighbor 10.0.3.1 activate
  neighbor 10.0.3.1 soft-reconfiguration inbound
  neighbor 10.0.3.1 route-map ROUTE_MAP_IN in
  neighbor 10.0.3.1 route-map ROUTE_MAP_OUT out
  
  bgp bestpath as-path multipath-relax
  maximum-paths 8
exit
