frr version 8.4
hostname meta
service integrated-vtysh-config

route-map ROUTE_MAP_IN permit 10
exit

ip prefix-list R6.1          permit 157.240.1.35/32
ip prefix-list R6.2          permit 157.240.1.36/32
ip prefix-list R6.3          permit 157.240.1.37/32

route-map ROUTE_MAP_OUT_R6_1 permit 10
 match ip address prefix-list R6.2
 set as-path prepend 32934
exit
route-map ROUTE_MAP_OUT_R6_1 permit 20
 match ip address prefix-list R6.3
 set as-path prepend 32934
exit
route-map ROUTE_MAP_OUT_R6_1 permit 30
exit


route-map ROUTE_MAP_OUT_R6_2 permit 10
 match ip address prefix-list R6.1
 set as-path prepend 32934
exit
route-map ROUTE_MAP_OUT_R6_2 permit 20
 match ip address prefix-list R6.3
 set as-path prepend 32934
exit
route-map ROUTE_MAP_OUT_R6_2 permit 30
exit


route-map ROUTE_MAP_OUT_R6_3 permit 10
 match ip address prefix-list R6.1
 set as-path prepend 32934
exit
route-map ROUTE_MAP_OUT_R6_3 permit 20
 match ip address prefix-list R6.2
 set as-path prepend 32934
exit
route-map ROUTE_MAP_OUT_R6_3 permit 30
exit



router bgp 32934
 bgp router-id 6.6.6.6
 bgp fast-external-failover
 no bgp ebgp-requires-policy
 
 neighbor 10.0.6.1 remote-as 205718
 neighbor 10.0.6.1 description R6.1
 neighbor 10.0.6.1 bfd

 neighbor 10.1.6.1 remote-as 205718
 neighbor 10.1.6.1 description R6.2
 neighbor 10.1.6.1 bfd

 neighbor 10.2.6.1 remote-as 205718
 neighbor 10.2.6.1 description R6.3
 neighbor 10.2.6.1 bfd
 
 address-family ipv4 unicast
  network 157.240.1.35/32
  network 157.240.1.36/32
  network 157.240.1.37/32
  
  neighbor 10.0.6.1 activate
  neighbor 10.0.6.1 soft-reconfiguration inbound
  neighbor 10.0.6.1 route-map ROUTE_MAP_IN in
  neighbor 10.0.6.1 route-map ROUTE_MAP_OUT_R6_1 out
  
  neighbor 10.1.6.1 activate
  neighbor 10.1.6.1 soft-reconfiguration inbound
  neighbor 10.1.6.1 route-map ROUTE_MAP_IN in
  neighbor 10.1.6.1 route-map ROUTE_MAP_OUT_R6_2 out
    
  neighbor 10.2.6.1 activate
  neighbor 10.2.6.1 soft-reconfiguration inbound
  neighbor 10.2.6.1 route-map ROUTE_MAP_IN in
  neighbor 10.2.6.1 route-map ROUTE_MAP_OUT_R6_3 out
  
  bgp bestpath as-path multipath-relax
  maximum-paths 8
exit
