frr version 8.4
hostname google
service integrated-vtysh-config

route-map ROUTE_MAP_IN permit 10
exit

ip prefix-list R6.1        permit 8.8.8.8/32
ip prefix-list R6.2        permit 8.8.4.4/32

route-map ROUTE_MAP_OUT_6_1 permit 10
 match ip address prefix-list R6.2
 set as-path prepend 15169
exit
route-map ROUTE_MAP_OUT_6_1 permit 20
exit

route-map ROUTE_MAP_OUT_6_2 permit 10
 match ip address prefix-list R6.1
 set as-path prepend 15169
exit
route-map ROUTE_MAP_OUT_6_2 permit 20
exit

router bgp 15169
 bgp router-id 4.4.4.4
 bgp fast-external-failover
 no bgp ebgp-requires-policy
 
 neighbor 10.0.4.1 remote-as 205718
 neighbor 10.0.4.1 description R6.1
 neighbor 10.0.4.1 bfd

 neighbor 10.1.4.1 remote-as 205718
 neighbor 10.1.4.1 description R6.2
 neighbor 10.1.4.1 bfd

 address-family ipv4 unicast
  network 8.8.8.8/32
  network 8.8.4.4/32
  
  neighbor 10.0.4.1 activate
  neighbor 10.0.4.1 soft-reconfiguration inbound
  neighbor 10.0.4.1 route-map ROUTE_MAP_IN in
  neighbor 10.0.4.1 route-map ROUTE_MAP_OUT_6_1 out
  
  neighbor 10.1.4.1 activate
  neighbor 10.1.4.1 soft-reconfiguration inbound
  neighbor 10.1.4.1 route-map ROUTE_MAP_IN in
  neighbor 10.1.4.1 route-map ROUTE_MAP_OUT_6_2 out
  
  bgp bestpath as-path multipath-relax
  maximum-paths 8
exit
